<?php
$ar = [100,200,400,800,900,3];
$arr = [100,200,30,400,50,600];
$data = ["GarRy" => 89, "rohit" => 85, "tushar" => 45,12,68,"harry" => 8];
//print_r(array_change_key_case($data,1));
//print_r(array_chunk($data,3));
//print_r(array_combine($ar,$arr));
//print_r(array_column($data,""));
//print_r(array_count_values($data));
//print_r(array_diff($arr,$ar));
//print_r(array_diff_assoc($arr,$ar));
//print_r(array_diff_key($arr,$ar));
$arrr = array_fill(5,8,89);
//print_r($arrr);
//print_r(array_intersect($ar,$arr));
//print_r(array_intersect_key($arr,$ar));
//print_r(array_intersect_assoc($arr,$ar));
//print_r(array_key_exists("harry",$data));
//print_r(array_flip($arr));
//print_r(array_keys($data));
//print_r(array_sum($arr));
//array_push($arr,"4");
//print_r ($arr);
//print_r(array_pop($ar));
//unset($arr[3]);
//print_r($arr);
//print_r(array_product($data));
//print_r(array_reverse($data));
//print_r(array_replace($arr,$ar));
//print_r(array_merge($arr,$ar));
//print_r(array_search(200,$arr));
//array_splice($arr,1,3,$ar);
//print_r($arr);
//print_r(array_slice($arr,"3"));
//shuffle($arr);
//print_r($arr);
//sort($arr);
//print_r($arr);
//rsort($arr);
//print_r($arr);
//ksort($data);
//print_r($data);
//krsort($data);
//print_r($data);
//asort($data);
//print_r($data);
//arsort($data);
//print_r($data);
//natcasesort($arr);
//print_r($arr);
foreach($arr as $key => $val);
?>